version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mega-mix"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g53xgeo0bjd"
s3_prefix = "mega-mix"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
